local path = minetest.get_modpath("player_mechanics")
dofile(path.."/version_info.lua")
dofile(path.."/player_interaction.lua")
dofile(path.."/player_mechanics.lua")
dofile(path.."/eating_mechanics.lua")
dofile(path.."/flowing.lua")
dofile(path.."/fall_damage.lua")
